### ISSUE TITLE
Fixer doesn't play well with rule-of-hooks and exhaustive-deps

### ISSUE THREAD

**Issue by macmccann** [arthurgeron/eslint-plugin-react-usememo#43]
Love the package! However, when I run the autofixer I've noticed a few issues:

1. The fixer will often violate the rules of hooks; e.g. create code like this:
```
  const optionRows = useMemo(() => {
    const els = options.map(({ label, selected }, index) => (
      <View
        style={useMemo(() => [styles.optionContainer, style], [])} // !! can't use useMemo here !!
      >
        <Text>{label}</Text>
      </View>
    ));
    return els;
  }, [options, handlePress, style]);
```

2. The fixer will often write code that doesn't pass exhaustive-deps, e.g.

```
const OpenWithMapsPopup: React.FC<OpenWithMapsPopupProps> = ({
  currentLocation,
}) => {
  const options = useMemo(
    () => ({
      sourceLatitude: currentLocation?.latitude,
      sourceLongitude: currentLocation?.longitude,
    }),
    [], // !! this is dangerous, currentLocation should be in the dependency array !!
  );
... return component
```

any guidance would be appreciated!

**Comment by arthurgeron** [comment]
Hey @macmccann, thank you for bringing this issue to light. You're right, though the problem is that inline JSX from iterations can never be "memo" safe; ideally, that logic would be extracted into another component, allowing the plugin to work correctly.

I'll see a way to detect if the rule's breakage comes from within an iteration or another useMemo/useCallback, disable the auto-fix, and create a custom warning for those two scenarios. I can't give you an ETA; feel free to help if you have the bandwidth.

Hopefully, what's planned for [3.0](https://github.com/users/arthurgeron/projects/1) will also avoid rule checking for props such as `style`, which generally don't have to be memoed.

**Comment by arthurgeron** [comment]
@macmccann I've published `v2.4.0--beta0`; it should fix your issue. Can you please validate it and give some feedback? Thanks

**Comment by macmccann** [comment]
I'll take a look, thanks!

**Comment by arthurgeron** [comment]
About the second case, it'd be redundant for the auto-fixer to repeat a behavior from react-hooks ESLint plugin. If that's something to be worried about, it'd be expected that the rule of hooks plugin is also being used, that said, I never intended for the code changed by the fixer to be something that'd go unsupervised.
